//! crates/engine/src/suricata.rs
//!
//! Manages Suricata IPS:
//!  1. Writes a minimal suricata.yaml config pointing at NFQUEUE 0.
//!  2. Spawns `suricata` as a child process.
//!  3. Tails /var/log/suricata/eve.json line-by-line and parses alerts.
//!  4. Pushes alerts into the shared Vec<Value> that the Axum API serves.
//!
//! HOW NFQUEUE WORKS
//! ─────────────────
//! nftables has `queue num 0 bypass` in the FORWARD chain (see nftables.rs).
//! The kernel holds each packet in the netfilter queue.  Suricata calls
//! nfqueue_get_packet(), inspects it, and calls nfqueue_set_verdict():
//!   • NF_ACCEPT  → packet continues through the stack (clean traffic)
//!   • NF_DROP    → packet is silently discarded (signature match)
//!
//! "bypass" in the nft rule means: if nothing is listening on queue 0,
//! packets are automatically accepted.  This gives fail-open behaviour during
//! Suricata restarts.  Without "bypass", the queue fills and the kernel drops
//! everything — that's fail-closed.

use anyhow::Result;
use serde_json::Value;
use std::{
    io::{BufRead, BufReader},
    path::Path,
    process::{Child, Command, Stdio},
    sync::Arc,
    time::Duration,
};
use tokio::{
    fs::File,
    io::{AsyncBufReadExt, BufReader as AsyncBufReader},
    sync::RwLock,
    time::sleep,
};
use tracing::{info, warn};

const EVE_JSON_PATH:  &str = "/var/log/suricata/eve.json";
const SURICATA_CONF:  &str = "/etc/suricata/linuxshield.yaml";
const ALERT_BUFFER:   usize = 1000; // keep last N alerts in memory

/// Entry point: write config, start Suricata, tail eve.json forever.
pub async fn run(alerts: Arc<RwLock<Vec<Value>>>) -> Result<()> {
    // Write minimal Suricata YAML config
    write_suricata_config()?;

    // Spawn Suricata (if it's already running as a system service, skip this)
    let use_system_suricata = std::env::var("LINUXSHIELD_SURICATA_SYSTEM")
        .map(|v| v == "1")
        .unwrap_or(false);

    if !use_system_suricata {
        tokio::spawn(async {
            spawn_suricata();
        });
        // Give Suricata a moment to start up before tailing eve.json
        sleep(Duration::from_secs(3)).await;
    }

    info!("Tailing Suricata eve.json at {}", EVE_JSON_PATH);
    tail_eve_json(alerts).await
}

/// Write a minimal Suricata configuration for NFQUEUE inline mode.
/// In production, merge this with the full suricata.yaml from your distro.
fn write_suricata_config() -> Result<()> {
    let config = r#"
# LinuxShield — minimal Suricata config for NFQUEUE inline IPS mode.
# Generated by linuxshield-engine. DO NOT EDIT manually.

vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "!$HOME_NET"
  port-groups:
    HTTP_PORTS: "80"
    HTTPS_PORTS: "443"

# NFQUEUE inline mode — Suricata reads packets from kernel queue 0.
# The nftables rule `queue num 0 bypass` feeds packets here.
nfq:
  mode: accept           # inline IPS: Suricata is the accept/drop decision maker
  fail-open: yes         # if Suricata crashes, packets pass (fail-open)

# Output: eve.json is the structured alert log we tail
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert:
            payload: no      # set yes to include packet payload in alerts
            metadata: yes
        - drop
        - stats:
            totals: yes

# Rule files — use the ET Open ruleset for a head start
rule-files:
  - /etc/suricata/rules/suricata.rules
  # Add custom rules here:
  # - /etc/suricata/rules/linuxshield-custom.rules

# Logging
logging:
  default-log-level: notice
  outputs:
    - console:
        enabled: yes
    - file:
        enabled: yes
        filename: /var/log/suricata/suricata.log
"#;

    std::fs::create_dir_all("/etc/suricata").ok();
    std::fs::write(SURICATA_CONF, config.trim())?;
    info!("Wrote Suricata config to {}", SURICATA_CONF);
    Ok(())
}

/// Spawn Suricata in NFQUEUE mode as a child process.
fn spawn_suricata() {
    info!("Spawning Suricata IPS (NFQUEUE mode)...");
    match Command::new("suricata")
        .args([
            "-c", SURICATA_CONF,
            "--nfq",          // NFQUEUE inline mode
            "-q", "0",        // listen on NFQUEUE 0 (matches the nftables rule)
            "--pidfile", "/run/suricata.pid",
        ])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
    {
        Ok(child) => info!("Suricata started with PID {}", child.id()),
        Err(e) => warn!("Failed to spawn Suricata: {} — is it installed?", e),
    }
}

/// Continuously tail eve.json and push alert events into the shared buffer.
/// Uses tokio async I/O so it doesn't block the engine's async runtime.
async fn tail_eve_json(alerts: Arc<RwLock<Vec<Value>>>) -> Result<()> {
    // Wait for the file to exist (Suricata creates it on first alert)
    loop {
        if Path::new(EVE_JSON_PATH).exists() {
            break;
        }
        sleep(Duration::from_secs(2)).await;
        info!("Waiting for {} to appear...", EVE_JSON_PATH);
    }

    let file = tokio::fs::File::open(EVE_JSON_PATH).await?;
    let mut reader = AsyncBufReader::new(file);
    let mut line  = String::new();

    // Seek to end so we only see NEW alerts, not historical ones.
    // (If you want to replay past alerts on restart, remove this seek.)
    let _ = reader.get_mut().seek(std::io::SeekFrom::End(0)).await;

    info!("Eve.json tail started");

    loop {
        line.clear();
        match reader.read_line(&mut line).await {
            Ok(0) => {
                // End of file — Suricata hasn't written a new line yet.
                sleep(Duration::from_millis(250)).await;
                continue;
            }
            Ok(_) => {
                let trimmed = line.trim();
                if trimmed.is_empty() {
                    continue;
                }

                // Parse the JSON line
                match serde_json::from_str::<Value>(trimmed) {
                    Ok(event) => {
                        // We're only interested in "alert" and "drop" events.
                        let event_type = event.get("event_type")
                            .and_then(Value::as_str)
                            .unwrap_or("");

                        if event_type == "alert" || event_type == "drop" {
                            let mut buf = alerts.write().await;
                            buf.push(event);
                            // Cap the buffer to avoid unbounded memory growth
                            if buf.len() > ALERT_BUFFER {
                                buf.drain(0..buf.len() - ALERT_BUFFER);
                            }
                        }
                    }
                    Err(e) => {
                        // Non-fatal: malformed line or partial write
                        warn!("Failed to parse eve.json line: {}", e);
                    }
                }
            }
            Err(e) => {
                warn!("Error reading eve.json: {} — retrying in 1s", e);
                sleep(Duration::from_secs(1)).await;
            }
        }
    }
}
